### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by adamhsparks** [jafernandez01/cndcR#2]
Sorry about overlooking the Zenodo badge and inst/CITATION.

But that does raise the question for me, these two things have different citations for presumably the same resource.

How should I cite this?

As Zenodo suggests,
@Misc{Fernandez2022b,
  author    = {Fernandez, Javier},
  title     = {jafernandez01/cndcR: v1.0.0},
  copyright = {Open Access},
  date      = {2022},
  doi       = {10.5281/ZENODO.6468142},
  publisher = {Zenodo},
}

Or as the `inst/CITATION` suggests,
@Article{Fernandez2022,
  author  = {Fernandez, Javier A. and van Versendaal, Emmanuela and Lacasa, Josefina and Makowski, David and Lemaire, Gilles and Ciampitti, Ignacio A.},
  journal = {European Journal of Agronomy},
  title   = {Dataset characteristics for the determination of critical nitrogen dilution curves: from the past to new guidelines},
  year    = {2022},
  volume  = {in revision},
}

thanks!

**Comment by jafernandez01** [comment]
Adam - 
Thanks for checking. Yes, the preferred citation for the package would be the publication in _European Journal of Agronomy_. 

Only in case source R-code or data from the repository is used, please also cite the repository from Zenodo. I have updated the `inst/CITATION`.

**Comment by adamhsparks** [comment]
Thank you, this is clear. I will cite both. On 25 Oct 2022, at 17:51, Javier Fernandez ***@***.***> wrote:﻿
Adam -
Thanks for checking. Yes, the preferred citation for the package would be the publication in European Journal of Agronomy.
Only in case source R-code or data from the repository is used, please also cite the repository from Zenodo. I have updated the inst/CITATION.
